# !/usr/bin/python3
""" This module defines a dictionnary that link the id of LaTeX figures to their labels. It can be automatically
generated by LaTeX.
You can then look for this function name in the file figures.py """
FIGURE = {}
# FIGURE["6"] = "fig_compare_discrete_modif"
#FIGURE["1"] = "fig_is_it_linear_enough"
FIGURE["1"] = "fig_evolution_err_nonlinear"
ALL_LABELS = FIGURE
