"""
    This module defines
    a dictionnary that link the id of LaTeX figures to their labels.
    Ideally, it will eventually be automatic in the future by
    analyzing an html file generated by LaTeX with show-labels package.
    Right now, I will just enter them by hand.
"""

ALL_LABELS = {}
ALL_LABELS["2"] = "fig_figure_2"
